### ISSUE TITLE
Newest docker container for Fermibottle Runtime Error

### ISSUE THREAD

**Issue by jleagle94** [fermi-lat/FermiBottle#10] opened 2021-03-03 20:45 UTC
Hello,

I am trying to figure out why I have a fermibottle container image on my Linux machine which works fine with the latest Fermipy 1.0.0 and Fermitools 2.0.0 but a Docker version on my local machine (OSX Catalina 10.15.7) which gives a runtime error when running `gta.setup()`.

This is the traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1081, in setup
    c.setup(overwrite=overwrite)
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 5111, in setup
    self._select_data(overwrite=overwrite, **kwargs)
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 5193, in _select_data
    loglevel=loglevel)
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 201, in run_gtapp
    filter_dict(kw, None)
  File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 227, in filter_dict
    for k, v in d.items():
RuntimeError: dictionary changed size during iteration
```

And versions of things:
```
(fermi) [fermi@1608251666ba old_pwn_analysis_msh1556]$ conda list fermi
# packages in environment at /opt/anaconda/envs/fermi:
#
# Name                    Version                   Build  Channel
fermipy                   1.0.0            py37h7b7c402_0    conda-forge
fermitools                2.0.0                hf484d3e_0    fermi
fermitools-data           0.18                          0    fermi
fermitools-dependencies   2.0.0                         0    fermi
(fermi) [fermi@1608251666ba old_pwn_analysis_msh1556]$ which python
/opt/anaconda/envs/fermi/bin/python
(fermi) [fermi@1608251666ba old_pwn_analysis_msh1556]$ python --version
Python 3.7.8
```
It is quite literally the exact same setup as I have on a Linux remote server. Does anyone have an idea why I get this error on my Mac but not the Linux?

**Comment by Areustle** [comment] 2021-03-03 20:57
Thanks for bringing this to our attention. I will see if I can replicate the issue and get back to you with a fix.

**Comment by Areustle** [comment] 2021-03-08 13:35
I'm working on a new version of the container which is updated for fermitools version 2.0.8 can you rerun your analysis with that container and let me know if you get the same error?

You can get it with  `docker pull fssc/fermibottle:dev`. You create and launch new containers using the same create/start/attach method, but add that `:dev` at the end of the create step.

**Comment by sstraal** [comment] 2021-03-10 12:27
Hi, 
I have been experiencing the same issue. I tried to get the new FermiBottle to work on both MacOS Catalina 10.15.7 and on MacOS Mojave 10.14.6, running into the same RuntimeError on the dictionary.

I've tried to get past this by creating a copy of the dictionary as suggested in https://github.com/fermiPy/fermipy/issues/369
I've tried changing "for k, v in d.items()" to
"for k, v in list(d.items()):"

Someone else suggested to try and change the code block to:
dcopy={**d}
for k,v in dcopy.items():
    if v == val:
       del d[k]

Which all did not work for me.

At first instance I ran into the same runtime error after installing the container on a Linux machine, running on Centos 7, but managed to fix it by trying the latter solution (adding "dcopy={**d}").

After much investigating I've found that more people experience this issue on MacOS, using different software, and that it was a known error in Python 3.7.5, however it should've been fixed in Python 3.7.8, which is the python version in the Fermibottle.

I hope this information can be useful in trying to find a fix.

**Comment by jleagle94** [comment] 2021-03-11 21:35
I think I may have found a solution. Thanks to @straal, I add not one but both of the solutions such that gtanalysis.py around L228 reads: 

```
dcopy={**d}
for k,v in list(dcopy.items()):
if v == val:
del d[k]
```

and I am now able to run Fermipy 1.0.0 fermibottle docker container!

**Comment by Areustle** [comment] 2021-04-08 18:34
Oh good, it was a fermipy bug, not a FermiBottle bug.

**Closed by Areustle** 2021-04-08 18:34 UTC

**Comment by abhiitk** [comment] 2021-09-20 21:12
> I think I may have found a solution. Thanks to @straal, I add not one but both of the solutions such that gtanalysis.py around L228 reads:
> 
> ```
> dcopy={**d}
> for k,v in list(dcopy.items()):
> if v == val:
> del d[k]
> ```
> 
> and I am now able to run Fermipy 1.0.0 fermibottle docker container on my Mac!

I have installed fermibottle and tried to run the analysis but got the same issue as your, I saw this thread but having a different issue, I am unable to understand why the terminal is showing 

> File "/opt/anaconda/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 227, in filter_dict
    for k, v in d.items():

I don't have that directory in my ubuntu at all, my packages are installed in anaconda3, I found the fermipy folder from the anaconda3 folder and did the suggested edits in the gtanalysis.py but the issue is not solved, and the error remains same.
Someone please help..
